/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:userGUI:502174:
  appc.background(230);
} //_CODE_:userGUI:502174:

public void simSpeed_change1(GSlider source, GEvent event) { //_CODE_:simulationSpeedSlider:531818:
  simulationSpeed = simulationSpeedSlider.getValueF();
} //_CODE_:simulationSpeedSlider:531818:

public void bSpawnRate_change1(GSlider source, GEvent event) { //_CODE_:beetleSpawnRateSlider:653785:
  s.beetleSpawnRate = 0.2 * beetleSpawnRateSlider.getValueF();
} //_CODE_:beetleSpawnRateSlider:653785:

public void fSpawnRate_change1(GSlider source, GEvent event) { //_CODE_:foodSpawnRateSlider:883490:
  s.foodSpawnRate = 0.4 * foodSpawnRateSlider.getValueF();
} //_CODE_:foodSpawnRateSlider:883490:

public void qSpawnRate_change1(GSlider source, GEvent event) { //_CODE_:queenSpawnRateSlider:691773:
  s.queenSpawnRate = (5 - queenSpawnRateSlider.getValueF())*15 + 90;
} //_CODE_:queenSpawnRateSlider:691773:

public void pausePlayButtonClick(GButton source, GEvent event) { //_CODE_:pausePlayButton:331840:
  paused = !paused;
  pausePlayButton.setText(pausePlayStrings[int(paused)]);
} //_CODE_:pausePlayButton:331840:

public void button1_click1(GButton source, GEvent event) { //_CODE_:restartButton:225406:
  simulationSpeed = 1;
  if (initialColonyNumText.getText().isEmpty()) startingColonyAmount = 1;
  else startingColonyAmount = Integer.parseInt(initialColonyNumText.getText());
  //println(initialColonyNumText.getText());
  s = new Simulation();
  paused = false;
  pausePlayButton.setText(pausePlayStrings[int(paused)]);
} //_CODE_:restartButton:225406:

public void initialColonyNum_change1(GTextField source, GEvent event) { //_CODE_:initialColonyNumText:417934:
  
} //_CODE_:initialColonyNumText:417934:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  userGUI = GWindow.getWindow(this, "Control Window", 0, 0, 320, 290, JAVA2D);
  userGUI.noLoop();
  userGUI.setActionOnClose(G4P.KEEP_OPEN);
  userGUI.addDrawHandler(this, "win_draw1");
  simulationSpeedSlider = new GSlider(userGUI, 30, 30, 100, 40, 10.0);
  simulationSpeedSlider.setShowLimits(true);
  simulationSpeedSlider.setLimits(1.0, 0.1, 2.0);
  simulationSpeedSlider.setNbrTicks(10);
  simulationSpeedSlider.setNumberFormat(G4P.DECIMAL, 2);
  simulationSpeedSlider.setLocalColorScheme(GCScheme.RED_SCHEME);
  simulationSpeedSlider.setOpaque(false);
  simulationSpeedSlider.addEventHandler(this, "simSpeed_change1");
  simSpeedLabel = new GLabel(userGUI, 20, 20, 120, 20);
  simSpeedLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  simSpeedLabel.setText("Simulation Speed");
  simSpeedLabel.setLocalColorScheme(GCScheme.RED_SCHEME);
  simSpeedLabel.setOpaque(false);
  beetleSpawnRateSlider = new GSlider(userGUI, 30, 120, 100, 40, 10.0);
  beetleSpawnRateSlider.setShowLimits(true);
  beetleSpawnRateSlider.setLimits(1, 0, 5);
  beetleSpawnRateSlider.setNumberFormat(G4P.INTEGER, 0);
  beetleSpawnRateSlider.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  beetleSpawnRateSlider.setOpaque(false);
  beetleSpawnRateSlider.addEventHandler(this, "bSpawnRate_change1");
  beetleSpawnRateLabel = new GLabel(userGUI, 20, 110, 120, 20);
  beetleSpawnRateLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  beetleSpawnRateLabel.setText("Beetle Spawn Rate");
  beetleSpawnRateLabel.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  beetleSpawnRateLabel.setOpaque(false);
  foodSpawnRateSlider = new GSlider(userGUI, 190, 30, 100, 40, 10.0);
  foodSpawnRateSlider.setShowLimits(true);
  foodSpawnRateSlider.setLimits(1, 0, 5);
  foodSpawnRateSlider.setNumberFormat(G4P.INTEGER, 0);
  foodSpawnRateSlider.setOpaque(false);
  foodSpawnRateSlider.addEventHandler(this, "fSpawnRate_change1");
  foodSpawnRateLabel = new GLabel(userGUI, 180, 20, 120, 20);
  foodSpawnRateLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  foodSpawnRateLabel.setText("Food Spawn Rate");
  foodSpawnRateLabel.setOpaque(false);
  queenSpawnRateSlider = new GSlider(userGUI, 190, 120, 100, 40, 10.0);
  queenSpawnRateSlider.setShowLimits(true);
  queenSpawnRateSlider.setLimits(5, 0, 10);
  queenSpawnRateSlider.setNumberFormat(G4P.INTEGER, 0);
  queenSpawnRateSlider.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  queenSpawnRateSlider.setOpaque(false);
  queenSpawnRateSlider.addEventHandler(this, "qSpawnRate_change1");
  queenSpawnRateLabel = new GLabel(userGUI, 180, 110, 120, 20);
  queenSpawnRateLabel.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  queenSpawnRateLabel.setText("Queen Spawn Rate");
  queenSpawnRateLabel.setLocalColorScheme(GCScheme.ORANGE_SCHEME);
  queenSpawnRateLabel.setOpaque(false);
  pausePlayButton = new GButton(userGUI, 50, 200, 80, 30);
  pausePlayButton.setText("Pause");
  pausePlayButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  pausePlayButton.addEventHandler(this, "pausePlayButtonClick");
  restartButton = new GButton(userGUI, 190, 200, 80, 30);
  restartButton.setText("Restart");
  restartButton.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  restartButton.addEventHandler(this, "button1_click1");
  label1 = new GLabel(userGUI, 80, 250, 130, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Initial Colony Number:");
  label1.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label1.setOpaque(false);
  initialColonyNumText = new GTextField(userGUI, 210, 250, 30, 20, G4P.SCROLLBARS_NONE);
  initialColonyNumText.setPromptText("1");
  initialColonyNumText.setOpaque(true);
  initialColonyNumText.addEventHandler(this, "initialColonyNum_change1");
  userGUI.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow userGUI;
GSlider simulationSpeedSlider; 
GLabel simSpeedLabel; 
GSlider beetleSpawnRateSlider; 
GLabel beetleSpawnRateLabel; 
GSlider foodSpawnRateSlider; 
GLabel foodSpawnRateLabel; 
GSlider queenSpawnRateSlider; 
GLabel queenSpawnRateLabel; 
GButton pausePlayButton; 
GButton restartButton; 
GLabel label1; 
GTextField initialColonyNumText; 
